# Generated by Django 4.2.10 on 2024-08-25 20:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='main_type',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='shop.productmodel'),
        ),
        migrations.AlterField(
            model_name='customattribute',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='file',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='/default/product-image.png', upload_to='product/img/'),
        ),
        migrations.DeleteModel(
            name='MainType',
        ),
    ]
