# Generated by Django 4.2.10 on 2024-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productcategorymodel_main_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rate',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
